CREATE TABLE credit_applications (
    id SERIAL PRIMARY KEY, -- Unique record ID (autogenerated)
    report_date DATE, -- Date on which the report is generated.
    report_country VARCHAR(50), -- Country for which this report is generated.
    report_portfolio VARCHAR(50), -- Portfolio name/type (e.g., Consumer Finance, Mortgage, etc.).
    tx_id VARCHAR(50) UNIQUE, -- Transaction ID. Unique application identifier.
    application_date DATE, -- Date of the loan application.
    main_channel VARCHAR(50), -- Main channel where application was initiated (e.g., Branch, Web, Mobile).
    subchannels VARCHAR(100), -- Sub-category of the main channel (e.g., Electronics, Home Furnishing, etc. for POS).
    purpose_of_loan VARCHAR(100), -- General purpose for requesting the loan (e.g., home renovation, car purchase, etc.).
    credit_bureau_null_flag SMALLINT, -- 1 if the applicant has no record in the credit bureau, 0 otherwise.
    internal_model_score DECIMAL(6,2), -- Internal credit score assigned to the applicant.
    expected_pd DECIMAL(5,4), -- Expected probability of default for the internal model.
    policy_rules_flag SMALLINT, -- 1 if the applicant hits a policy rule from global rules, 0 otherwise.
    other_rule_flag SMALLINT, -- 1 if the applicant hits a rule outside policy/fraud/global rules, 0 otherwise.
    fraud_rule_flag SMALLINT, -- 1 if the applicant hits a fraud rule, 0 otherwise.
    score_decline_flag SMALLINT, -- 1 if the application is rejected because of a score cut-off, 0 otherwise.
    application_status VARCHAR(30), -- Current status of the application (e.g., Rejected, Accepted, Disbursed, In Process).
    credit_bureau_query SMALLINT, -- 0 if call to credit bureau was successful, -99 otherwise.
    credit_bureau_score DECIMAL(6,2), -- Credit score provided by the credit bureau for this applicant.
    credit_bureau_response_id INTEGER, -- Reference to the detailed response from credit bureau (actual details stored in another table, to be added later).
    other_credit_bureau_scores VARCHAR(100), -- Other scores provided by the credit bureau, if available.
    rule_details_id INTEGER, -- Reference to all triggered rules (actual rule details stored in another table, to be added later).
    affordability_flag SMALLINT, -- 1 if application is rejected based on affordability, 0 otherwise.
    net_income DECIMAL(12,2), -- Net income of the applicant.
    net_expenditure DECIMAL(12,2), -- Net expenditure of the applicant.
    branch_id VARCHAR(20), -- ID of the branch if the application originated from a branch.
    branch_name VARCHAR(50), -- Name of the branch where the application was made, if applicable.
    region_name VARCHAR(50), -- Name of the region where the branch is located, if applicable.
    cash_collateral DECIMAL(12,2), -- Amount of cash collateral if the loan is disbursed with collateral; 0 otherwise.
    time_with_bank DATE, -- Date when the applicant opened their account with the bank (i.e., relationship start date).
    auto_decision_flag SMALLINT, -- 1 if decision on the application was made automatically, 0 otherwise.
    created_at TIMESTAMP DEFAULT now(), -- Record creation timestamp.
    updated_at TIMESTAMP DEFAULT now() -- Last updated timestamp for the record.
);

-- Column documentation in database (PostgreSQL COMMENT ON COLUMN syntax):

COMMENT ON COLUMN credit_applications.report_date IS 'Date on which the report is generated.';
COMMENT ON COLUMN credit_applications.report_country IS 'Country for which this report is generated.';
COMMENT ON COLUMN credit_applications.report_portfolio IS 'Portfolio name/type (e.g., Consumer Finance, Mortgage, etc.).';
COMMENT ON COLUMN credit_applications.tx_id IS 'Transaction ID. Unique application identifier.';
COMMENT ON COLUMN credit_applications.application_date IS 'Date of the loan application.';
COMMENT ON COLUMN credit_applications.main_channel IS 'Main channel where application was initiated (e.g., Branch, Web, Mobile).';
COMMENT ON COLUMN credit_applications.subchannels IS 'Sub-category of the main channel (e.g., Electronics, Home Furnishing, etc. for POS).';
COMMENT ON COLUMN credit_applications.purpose_of_loan IS 'General purpose for requesting the loan (e.g., home renovation, car purchase, etc.).';
COMMENT ON COLUMN credit_applications.credit_bureau_null_flag IS '1 if the applicant has no record in the credit bureau, 0 otherwise.';
COMMENT ON COLUMN credit_applications.internal_model_score IS 'Internal credit score assigned to the applicant.';
COMMENT ON COLUMN credit_applications.expected_pd IS 'Expected probability of default for the internal model.';
COMMENT ON COLUMN credit_applications.policy_rules_flag IS '1 if the applicant hits a policy rule from global rules, 0 otherwise.';
COMMENT ON COLUMN credit_applications.other_rule_flag IS '1 if the applicant hits a rule outside policy/fraud/global rules, 0 otherwise.';
COMMENT ON COLUMN credit_applications.fraud_rule_flag IS '1 if the applicant hits a fraud rule, 0 otherwise.';
COMMENT ON COLUMN credit_applications.score_decline_flag IS '1 if the application is rejected because of a score cut-off, 0 otherwise.';
COMMENT ON COLUMN credit_applications.application_status IS 'Current status of the application (e.g., Rejected, Accepted, Disbursed, In Process).';
COMMENT ON COLUMN credit_applications.credit_bureau_query IS '0 if call to credit bureau was successful, -99 otherwise.';
COMMENT ON COLUMN credit_applications.credit_bureau_score IS 'Credit score provided by the credit bureau for this applicant.';
COMMENT ON COLUMN credit_applications.credit_bureau_response_id IS 'Reference to the detailed response from credit bureau (actual details stored in another table, to be added later).';
COMMENT ON COLUMN credit_applications.other_credit_bureau_scores IS 'Other scores provided by the credit bureau, if available.';
COMMENT ON COLUMN credit_applications.rule_details_id IS 'Reference to all triggered rules (actual rule details stored in another table, to be added later).';
COMMENT ON COLUMN credit_applications.affordability_flag IS '1 if application is rejected based on affordability, 0 otherwise.';
COMMENT ON COLUMN credit_applications.net_income IS 'Net income of the applicant.';
COMMENT ON COLUMN credit_applications.net_expenditure IS 'Net expenditure of the applicant.';
COMMENT ON COLUMN credit_applications.branch_id IS 'ID of the branch if the application originated from a branch.';
COMMENT ON COLUMN credit_applications.branch_name IS 'Name of the branch where the application was made, if applicable.';
COMMENT ON COLUMN credit_applications.region_name IS 'Name of the region where the branch is located, if applicable.';
COMMENT ON COLUMN credit_applications.cash_collateral IS 'Amount of cash collateral if the loan is disbursed with collateral; 0 otherwise.';
COMMENT ON COLUMN credit_applications.time_with_bank IS 'Date when the applicant opened their account with the bank (i.e., relationship start date).';
COMMENT ON COLUMN credit_applications.auto_decision_flag IS '1 if decision on the application was made automatically, 0 otherwise.';
COMMENT ON COLUMN credit_applications.created_at IS 'Record creation timestamp.';
COMMENT ON COLUMN credit_applications.updated_at IS 'Last updated timestamp for the record.';
